// Database service for TerminiYt.com - now using Prisma
import { db } from "./database-prisma"
import type { Business, Category, Service } from "./database"

// Export the database service as the main data source
export { db }

// For backward compatibility, export categories from database
export const getCategories = () => db.getCategories()
export const getBusinesses = (filters?: any) => db.getBusinesses(filters)
export const getBusinessById = (id: string) => db.getBusinessById(id)
export const getServicesByBusinessId = (businessId: string) => db.getServicesByBusinessId(businessId)
export const createBusiness = (business: any) => db.createBusiness(business)
export const createBooking = (booking: any) => db.createBooking(booking)
export const getBookingsByBusinessId = (businessId: string) => db.getBookingsByBusinessId(businessId)
export const getBusinessHours = (businessId: string) => db.getBusinessHours(businessId)

// Mock data for development and testing (fallback)

export const mockBusinesses: Business[] = [
  {
    id: "1",
    name: "Barber Elite",
    description: "Shërbime premium parukarie me stile tradicionale dhe moderne",
    category_id: "1",
    owner_name: "Gjon Smiti",
    email: "gjon@parukariaelite.com",
    phone: "+383 44 123 456",
    address: "123 Rruga e Pavarësisë, Qendra e Mitrovicës",
    city: "Mitrovicë",
    state: "Kosovë",
    google_maps_link: "https://maps.google.com/example1",
    latitude: 42.8833,
    longitude: 20.8667,
    website: "https://parukariaelite.com",
    instagram: "@parukariaelite",
    facebook: "ParukariaElite",
    is_verified: true,
    is_active: true,
    rating: 4.8,
    total_reviews: 127,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Studiu i Bukurisë Glamour",
    description: "Salon bukurie me shërbime të plota për flokë, thonj dhe kujdesin e lëkurës",
    category_id: "2",
    owner_name: "Sara Gjoni",
    email: "sara@studiubukuriseglamour.com",
    phone: "+383 44 234 567",
    address: "456 Rruga e Republikës, Pjesa e Re e Mitrovicës",
    city: "Mitrovicë",
    state: "Kosovë",
    google_maps_link: "https://maps.google.com/example2",
    latitude: 42.8843,
    longitude: 20.8677,
    website: "https://studiubukuriseglamour.com",
    instagram: "@studiubukuriseglamour",
    facebook: "StudiuBukuriseGlamour",
    is_verified: true,
    is_active: true,
    rating: 4.9,
    total_reviews: 89,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Qendra Mjekësore Shëndeti i Parë",
    description: "Shërbime mjekësore gjithëpërfshirëse me profesionistë me përvojë",
    category_id: "3",
    owner_name: "Dr. Mikel Brauni",
    email: "info@qendramjekesoreshendetipare.com",
    phone: "+383 44 345 678",
    address: "789 Spitali i Mitrovicës, Rrethi i Shëndetësisë",
    city: "Mitrovicë",
    state: "Kosovë",
    google_maps_link: "https://maps.google.com/example3",
    latitude: 42.8853,
    longitude: 20.8687,
    is_verified: true,
    is_active: true,
    rating: 4.7,
    total_reviews: 203,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Restorant Mitrovica",
    description: "Kuzhina tradicionale kosovare me shije autentike",
    category_id: "4",
    owner_name: "Bekim Krasniqi",
    email: "info@restorantmitrovica.com",
    phone: "+383 44 456 789",
    address: "321 Rruga e Qytetit, Qendra e Mitrovicës",
    city: "Mitrovicë",
    state: "Kosovë",
    google_maps_link: "https://maps.google.com/example4",
    latitude: 42.8863,
    longitude: 20.8697,
    website: "https://restorantmitrovica.com",
    instagram: "@restorantmitrovica",
    facebook: "RestorantMitrovica",
    is_verified: true,
    is_active: true,
    rating: 4.6,
    total_reviews: 156,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Fitness Center Mitrovica",
    description: "Qendër fitnesi moderne me pajisje të fundit",
    category_id: "5",
    owner_name: "Artan Berisha",
    email: "info@fitnesscentermitrovica.com",
    phone: "+383 44 567 890",
    address: "654 Rruga e Sportit, Kompleksi Sportiv",
    city: "Mitrovicë",
    state: "Kosovë",
    google_maps_link: "https://maps.google.com/example5",
    latitude: 42.8873,
    longitude: 20.8707,
    website: "https://fitnesscentermitrovica.com",
    instagram: "@fitnesscentermitrovica",
    facebook: "FitnessCenterMitrovica",
    is_verified: true,
    is_active: true,
    rating: 4.5,
    total_reviews: 98,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Auto Servis Mitrovica",
    description: "Shërbime të plota për mirëmbajtjen e automjeteve",
    category_id: "6",
    owner_name: "Driton Shala",
    email: "info@autoservismitrovica.com",
    phone: "+383 44 678 901",
    address: "987 Rruga e Industrisë, Zona Industriale",
    city: "Mitrovicë",
    state: "Kosovë",
    google_maps_link: "https://maps.google.com/example6",
    latitude: 42.8883,
    longitude: 20.8717,
    website: "https://autoservismitrovica.com",
    instagram: "@autoservismitrovica",
    facebook: "AutoServisMitrovica",
    is_verified: true,
    is_active: true,
    rating: 4.4,
    total_reviews: 73,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Hotel Mitrovica",
    description: "Hotel modern me shërbime të plota për vizitorët",
    category_id: "7",
    owner_name: "Valon Rexhepi",
    email: "info@hotelmitrovica.com",
    phone: "+383 44 789 012",
    address: "147 Rruga e Hoteleve, Qendra Turistike",
    city: "Mitrovicë",
    state: "Kosovë",
    google_maps_link: "https://maps.google.com/example7",
    latitude: 42.8893,
    longitude: 20.8727,
    website: "https://hotelmitrovica.com",
    instagram: "@hotelmitrovica",
    facebook: "HotelMitrovica",
    is_verified: true,
    is_active: true,
    rating: 4.3,
    total_reviews: 112,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Salon Prishtina",
    description: "Salon bukurie modern në qendër të Prishtinës",
    category_id: "2",
    owner_name: "Arta Krasniqi",
    email: "info@salonprishtina.com",
    phone: "+383 44 890 123",
    address: "123 Rruga Nëna Terezë, Qendra e Prishtinës",
    city: "Prishtinë",
    state: "Kosovë",
    google_maps_link: "https://maps.google.com/example8",
    latitude: 42.6629,
    longitude: 21.1655,
    website: "https://salonprishtina.com",
    instagram: "@salonprishtina",
    facebook: "SalonPrishtina",
    is_verified: true,
    is_active: true,
    rating: 4.7,
    total_reviews: 89,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockServices: Service[] = [
  {
    id: "1",
    business_id: "1",
    name: "Fshirje Flokësh Klasike",
    description: "Fshirje flokësh tradicionale parukarie me stilizim",
    price: 35,
    duration_minutes: 45,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    business_id: "1",
    name: "Trim & Stilizim i Mjekrës",
    description: "Trim dhe stilizim profesional i mjekrës",
    price: 25,
    duration_minutes: 30,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    business_id: "2",
    name: "Fshirje & Stilizim i Flokëve",
    description: "Fshirje dhe stilizim profesional i flokëve",
    price: 65,
    duration_minutes: 90,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
